site_name: Zhad Tech Library
site_url: https://zhadtech.github.io/
site_author: Zhad Tech
site_description: >
  A collection of documentation and guides for Zhad Tech projects.


theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    
# plugins:
#   - search
#   - sitemap
#   - social-preview
#   - social-preview

