site_name: Ghibli Library
site_url: https://zhadtech.github.io/ghibli-mkdocs-library/
site_author: Zhad
site_description: >
  An mkdocs library template made by Zhad Tech.

# Define docs directory
docs_dir: docs

theme:
  name: material
  custom_dir: custom_theme
  palette:
    # Palette toggle for Ghibli light mode
    - scheme: ghibli-light
      toggle:
        icon: material/weather-sunny
        name: Switch to Ghibli night mode
    
    # Palette toggle for Ghibli dark mode
    - scheme: ghibli-dark
      toggle:
        icon: material/weather-night
        name: Switch to Ghibli day mode

  # Additional customizations for Ghibli theme
  font:
    text: Nunito
    code: Roboto Mono
  
  # Code block features
  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight

# Enable syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Add custom CSS from the custom theme directory with version for cache busting
extra_css:
  - css/main.css
    
plugins:
  - search
  - mermaid2:
      version: 10.6.1
      arguments:
        securityLevel: 'tight'
        theme: 'default'
